development:
  archivist:
    - archivist1@example.com
  admin:
    - harry@hogwarts.edu
    - roger@umich.edu
    - njaffer@umich.edu
    - blancoj@umich.edu
    - gordonl@umich.edu
    - krenee@umich.edu
    - khage@umich.edu
    - jweise@umich.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
