# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6e8f8db72309ca76058b14484d559f9d22f11b547add88fa8b17b90d02ff523a2053e3ccda3eb1e7ea5e085a61724c85e1a084279eb4238b2ffe5c5ea908c35

test:
  secret_key_base: 0f8d94d10422ecfdddc5842d8115811dd6d91696ff40bf27caa6f3e15faa5d255833e99a528c0c71d9373f09c244f5a98489fb33168398a25d718aba88cbeffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
